#!/usr/bin/env python
# -*- coding: utf-8 -*-
# by Zhang Yi


# 测试一下
import cv2
import numpy as np

img = cv2.imread("2.jpg")
cv2.imwrite("canny.jpg",cv2.Canny(img,200,300))
cv2.imshow("canny",cv2.imread("canny.jpg"))
cv2.waitKey()
cv2.destroyAllWindows()

